name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Fetch QCBOR
      uses: actions/checkout@v3
      with:
        repository: laurencelundblade/QCBOR
        path: QCBOR

    - name: Install QCBOR
      run: |
        cd QCBOR
        make -j$(nproc)
        sudo make install PREFIX=/usr/local

    - name: Build t_cose
      run: |
        set -ex
        mkdir build
        cd build
        cmake -DCRYPTO_PROVIDER=Test -DQCBOR_ROOT=/usr/local ..
        make -j $(nproc)

    - name: Run tests
      run: build/t_cose_test

  mbedtls:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Fetch QCBOR
      uses: actions/checkout@v3
      with:
        repository: laurencelundblade/QCBOR
        path: QCBOR

    - name: Install QCBOR
      run: |
        cd QCBOR
        make -j$(nproc)
        sudo make install PREFIX=/usr/local

    - name: Fetch mbedTLS
      uses: actions/checkout@v3
      with:
        repository: ARMmbed/mbedtls
        ref: v2.28.0
        path: mbedtls

    - name: Install mbedTLS
      run: |
        cd mbedtls
        make -j $(nproc)
        sudo make install DESTDIR=/usr/local

    - name: Build t_cose
      run: |
        set -ex
        mkdir build
        cd build
        cmake -DCRYPTO_PROVIDER=MbedTLS -DQCBOR_ROOT=/usr/local -DMbedTLS_ROOT=/usr/local ..
        make -j $(nproc)

    - name: Run example
      run: build/t_cose_basic_example_psa

    - name: Run tests
      run: build/t_cose_test
    
  openssl:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Fetch QCBOR
      uses: actions/checkout@v3
      with:
        repository: laurencelundblade/QCBOR
        path: QCBOR

    - name: Install QCBOR
      run: |
        cd QCBOR
        make -j$(nproc)
        sudo make install PREFIX=/usr/local

    - name: Build t_cose
      run: |
        set -ex
        mkdir build
        cd build
        cmake -DCRYPTO_PROVIDER=OpenSSL -DQCBOR_ROOT=/usr/local ..
        make -j $(nproc)
    
    - name: Run example
      run: build/t_cose_basic_example_ossl
    
    - name: Run tests
      run: build/t_cose_test
    